FROM golang:1.20 AS build

ARG RELEASE=0.53.2

RUN git clone -b v${RELEASE} https://github.com/fatedier/frp.git /building \
        && cd /building \
        && make frps

FROM clibing/alpine

LABEL maintainer="clibing <wmsjhappy@gmail.com>"

COPY --from=build /building/bin/frps /bin/frps

COPY --from=build /building/conf/frps.ini /etc/frps.ini

COPY --from=build /building/conf/frps_full.ini /etc/frps_full.ini

CMD ["/bin/frps", "-c", "/etc/frps.ini"]

