name: ci

on:
  push:
    branches:
      - "main"
      - "master"

env:
  all: "skip"
  alpine: "run"
  alpine_coredns: "run"
  alpine_coredns_image: "clibing/alpine-coredns"
  alpine_coredns_version: "v1.10.0"

  alpine_docker: "skip"
  alpine_docker_image: "clibing/alpine-docker"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push alpine
        uses: docker/build-push-action@v3
        if: ${{ env.all == 'run' || env.alpine == 'run' }}
        with:
          context: alpine
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: true
          tags: clibing/alpine:latest, clibing/alpine:3.17, clibing/alpine:3.17.1
          build-args: |
            ALPINE_VERSION=3.17.1
      -
        name: Build and push alpine coredns
        uses: docker/build-push-action@v3
        if: ${{ env.all == 'run' || env.alpine_coredns == 'run' }}
        with:
          context: alpine-coredns
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ env.alpine_coredns_image }}:latest,${{ env.alpine_coredns_image }}:${{ env.alpine_coredns_version }}
          build-args: |
            COREDNS_VERSION=${{ env.alpine_coredns_version }}
      -
        name: Build and push alpine docker 
        uses: docker/build-push-action@v3
        if: ${{ env.all == 'run' || env.alpine_docker == 'run' }}
        with:
          context: alpine-docker
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ env.alpine_docker_image }}:latest

